### ISSUE TITLE
Static Compilation

### ISSUE THREAD

**Issue by BryanHurst** [NAVADMC/ADSM-CEngine#3]
We need to ensure that both the Linux and Windows compiles are static binaries that can run standalone.

**Comment by BryanHurst** [comment]
@ndh2 tried Statifier, and it didn't work.

Next he tried Ermine with a but more success. However, the trial version was used which caused issues when extra "THIS IS A TRIAL" text was sent to stdout.

**Comment by BryanHurst** [comment]
A note on static compilation: 

It is important from the "customer's" point that we do compile everything statically and not require that additional libraries be installed or compiled on their computer.
This is because of the target audience being in epidemiology and potentially using other related software, and other users being software developers/IT server managers. All of these categories of users could potentially have other versions of certain dependencies installed.

We do NOT want to suddenly upgrade their versions in case it breaks their other applications, and we cannot use older versions due to specific requirements of our software.

So we should compile all requirements statically and distribute the compiled libraries with the ADSM software.

This is why we have the .exe installer program for Windows.

**Comment by missyschoenbaum** [comment]
Moving this to ADSM repo and closing #844
