### ISSUE TITLE
Vaccinate By Priority Bucket Assertion Failed

### ISSUE THREAD

**Issue by BryanHurst** [NAVADMC/ADSM-CEngine#8]
Any time we run a simulation, the following error is thrown multiple times.

`ERROR:../modules/resources_and_implementation_of_controls_model.c:1602:vaccinate_by_priority: assertion failed: (bucket != NULL)`

Research needs to be done to see if this is adversely changing the simulation output, or if it is essentially a warning?

**Comment by missyschoenbaum** [comment]
It is adversely changing the simulation output.

**Comment by missyschoenbaum** [comment]
Moved into ADSM repo for tracking #841
